(()=>{
const $=id=>document.getElementById(id),dialog=$('welcomeDialog');
const questions=[['你想拍一个什么场景？','地点、空间关系和必要陈设，说得简单一点就好。','例如：一艘蒸汽小船，船舱连接前甲板。舱内有床、柜子，甲板有烟囱和木箱。'],['画面里有几个人？','说明人数、角色区别，也可以加入飞机、车辆或动物。','例如：2 个人，红色主角、蓝色船员；头顶有一架飞机。'],['他们会做什么？','按先后顺序说动作和节奏，关键帧之后还可以改。','例如：10 秒。主角跑出船舱，船员让开，主角停在甲板抬头，飞机从左向右掠过。'],['你希望镜头怎么走？','描述起点、朝向和大致路线。也可以先留给手机自由运镜。','例如：从主角身后跟出船舱，到甲板后向上仰拍飞机。']];
let step=0,answers=['','','',''],state={},signature='',pending=null,submissionId=null,replyPending=null,initialized=false;
try{const draft=JSON.parse(localStorage.getItem('dkyj-brief-draft')||'null');if(Array.isArray(draft)&&draft.length===4&&draft.every(x=>typeof x==='string'))answers=draft}catch{}
function saveDraft(){try{localStorage.setItem('dkyj-brief-draft',JSON.stringify(answers))}catch{}}
function say(s){$('briefFeedback').textContent=s}
function mode(tasks){$('briefForm').hidden=tasks;$('briefTasks').hidden=!tasks;$('briefNewTab').classList.toggle('selected',!tasks);$('briefTasksTab').classList.toggle('selected',tasks)}
function draw(){const review=step===4;$('briefQuestion').textContent=review?'这场戏，准备这样开始。':questions[step][0];$('briefHint').textContent=review?'选择要复用的模型。Agent 会在独立方案里继续制作。':questions[step][1];$('briefAnswer').hidden=review;$('briefAnswerLabel').hidden=review;$('briefAnswer').required=!review;$('briefReview').hidden=!review;$('briefBack').disabled=step===0;$('briefStep').textContent=review?'确认简报':`${step+1} / 4`;$('briefNext').textContent=review?'交给 Agent →':'下一步 →';$('briefConversation').replaceChildren();
if(step>0&&!review){const q=document.createElement('p');q.className='brief-previous';q.textContent=answers[step-1];$('briefConversation').append(q)}
if(!review){$('briefAnswer').value=answers[step];$('briefAnswer').placeholder=questions[step][2];$('briefAnswer').maxLength=[2000,1000,2000,1000][step]}else{const box=$('briefReview');box.replaceChildren();answers.forEach((a,i)=>{const p=document.createElement('p');const b=document.createElement('b');b.textContent=['场景','人物','动作','镜头'][i];p.append(b,document.createTextNode(a||'手机自由运镜'));box.append(p)});const label=document.createElement('label');label.textContent='复用模型';const select=document.createElement('select');select.id='briefSource';for(const p of state.projects?.items||[])if(p.available)select.add(new Option(p.name,p.id));select.value=state.projects?.active||'';label.append(select);box.append(label)} }
function show(){if(window.previsOverview?.canSwitchProject?.()===false){say('请先保存空间编辑');return}if(!dialog.open)dialog.showModal();window.dispatchEvent(new CustomEvent('previs-overview-editing',{detail:true}));}
$('welcomeBtn').onclick=show;$('welcomeHome').onclick=e=>{e.preventDefault();mode(false)};$('welcomeClose').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{window.dispatchEvent(new CustomEvent('previs-overview-editing',{detail:false}));try{localStorage.setItem('dkyj-welcome-seen','1')}catch{}});
$('briefNewTab').onclick=()=>mode(false);$('briefTasksTab').onclick=()=>mode(true);
$('briefBack').onclick=()=>{if(step<4)answers[step]=$('briefAnswer').value.trim();step=Math.max(0,step-1);draw()};
$('briefAnswer').addEventListener('input',()=>{answers[step]=$('briefAnswer').value;saveDraft()});
$('briefForm').onsubmit=e=>{e.preventDefault();if(pending)return;if(step<4){answers[step]=$('briefAnswer').value.trim();if(!answers[step])return;saveDraft();step++;draw();if(step<4)$('briefAnswer').focus();return}if(!state.connected){say('请先启动并连接 Blender 导演台');return}const id=submissionId||('brief-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10));submissionId=id;pending={id,previousError:state.error,started:Date.now()};$('briefNext').disabled=true;window.previsControl({type:'brief_create',id,scene:answers[0],characters:answers[1],action:answers[2],camera:answers[3],source:$('briefSource').value});say('正在保存创作任务…')};
$('copyAgentPrompt').onclick=async()=>{try{await navigator.clipboard.writeText($('agentPrompt').value);say('已复制，在 Agent 对话里发送即可')}catch{$('agentPrompt').select();say('请复制选中的文字，发给你的 Agent')}};
const labels={waiting:'等待 Agent',working:'制作中',needs_input:'需要你补充',ready:'可预演',failed:'制作未完成'};
function tasks(){const data=state.briefs||{items:[]};$('briefCount').textContent=data.items.length;const sig=JSON.stringify(data);if(sig===signature)return;signature=sig;if(data.items.length)say(labels[data.items[data.items.length-1].status]+' · 创作任务已保存在本机');const list=$('briefTaskList');list.replaceChildren();if(!data.items.length){const p=document.createElement('p');p.className='brief-empty';p.textContent='还没有创作任务。先描述一场戏吧。';list.append(p)}for(const b of [...data.items].reverse()){const card=document.createElement('article');card.className='brief-task';const tag=document.createElement('span');tag.className='brief-state state-'+b.status;tag.textContent=labels[b.status];const h=document.createElement('h3');h.textContent=b.scene;const desc=document.createElement('p');desc.textContent=b.characters+' · '+b.action;card.append(tag,h,desc);for(const m of b.messages){const p=document.createElement('p');p.className='brief-message '+m.role;p.textContent=(m.role==='agent'?'Agent：':'你：')+m.text;card.append(p)}if(b.status==='waiting'){const note=document.createElement('small');note.textContent='任务已保存。请在已配置的 Agent 对话中发送“执行下一个创作任务”。';card.append(note)}if(b.status==='ready'){const btn=document.createElement('button');btn.textContent='打开项目，开始预演 ↗';btn.disabled=state.recording||state.export?.status==='running';btn.onclick=()=>{window.previsControl({type:'project_switch',id:b.project_id});dialog.close()};card.append(btn)}if(b.status!=='working'){const form=document.createElement('form');form.className='brief-reply';const input=document.createElement('input');input.placeholder=b.status==='needs_input'?'回答 Agent 的问题…':'补充或调整这场戏…';input.setAttribute('aria-label','补充任务 '+b.id);input.maxLength=2000;input.required=true;const btn=document.createElement('button');btn.textContent='发送';form.append(input,btn);form.onsubmit=e=>{e.preventDefault();if(replyPending)return;replyPending={revision:state.briefs.revision,previousError:state.error,started:Date.now()};window.previsControl({type:'brief_reply',id:b.id,message:input.value});btn.disabled=true;say('正在发送补充说明，等待 Agent 继续…')};card.append(form)}list.append(card)}}
window.previsWelcome={render(s){state=s;if(!initialized){initialized=true;try{if(!s.recording&&s.export?.status!=='running'&&!localStorage.getItem('dkyj-welcome-seen'))show()}catch{if(!s.recording)show()}}$('welcomeConnection').textContent=s.connected?'● 本机 Blender 已连接 · '+(s.projects?.items.length||0)+' 个项目':'等待本机 Blender 连接';$('welcomeBtn').disabled=s.recording||s.export?.status==='running'||window.previsOverview?.canSwitchProject?.()===false;
if(pending){if(s.briefs?.items.some(b=>b.id===pending.id)){pending=null;submissionId=null;answers=['','','',''];saveDraft();step=0;draw();mode(true);$('briefNext').disabled=false;say('创作任务已保存，等待你的 Agent 接手。')}else if((s.error&&s.error!==pending.previousError)||Date.now()-pending.started>15000){say(s.error||'保存尚未确认，请先检查创作任务列表');pending=null;$('briefNext').disabled=false}}if(replyPending){if(s.briefs.revision>replyPending.revision)replyPending=null;else if((s.error&&s.error!==replyPending.previousError)||Date.now()-replyPending.started>15000){replyPending=null;signature='';say(s.error||'补充说明尚未确认，请检查任务记录')}}tasks()}};
draw();
})();
